# まずはファイルリスト
# それからコピー
# numpyのスライスを利用して

In [6]:
import pandas as pd
import numpy as np
import csv
import math
import matplotlib.pyplot as plt
import glob
import re
import os
import h5py

import matplotlib.pyplot as plt
# import skimage
from skimage import data, color
from skimage.transform import rescale, resize, downscale_local_mean
from skimage.viewer import ImageViewer
from skimage import io
import shutil

# 0.まずは，対象ディレクトリ移動(そして，その確認）か？


In [1]:
%cd C:\Users\survey\Dropbox\My PC (SURVEY-C20)\Documents\GitHub\continuous_multiple_files_cp

C:\Users\survey\Dropbox\My PC (SURVEY-C20)\Documents\GitHub\continuous_multiple_files_cp


In [3]:
%pwd

'C:\\Users\\survey\\Dropbox\\My PC (SURVEY-C20)\\Documents\\GitHub\\continuous_multiple_files_cp'

# ↑　移動しましたか？

# globを使って，単に，（ここではjpgの)ファイルリストを取得し，表示する．
# 応用的には，pandaのdataframe化した方がいいかな

In [4]:
l=glob.glob('*.txt')

In [5]:
print(l)

['1.txt', '2.txt', '3.txt', '4.txt']


In [7]:
print(l[1])

2.txt


# i.1 空リスト(画像ファイルリストを入れるため）を作成

In [9]:
file_list=list()

In [12]:
ext='txt'


# globで，特定のフォルダにある．jpgファイルを読み込む
# リスト（画像のファイル）作成のため，繰り返し処理する（リスト化も）
## 上で作成した(空)リストに，読み込んだリスト（ファイル名）を繰り返し<span style="color: yellow; ">追記</span>する．
## しかも，<span style="color: yellow; ">「拡張子」を省いた</span>ファイル名で

In [16]:
file_list=list()

for p in glob.glob('*.'+ext, recursive=True):
# for p in glob.glob('**.txt', recursive=True):
       if os.path.isfile(p):
           # print(os.path.basename(p))
           base_name=p.split('.',1)[0]
           file_list.append(base_name)
           print(base_name)

1
2
3
4


# ファイル名（拡張子なし）のリスト化終了

In [17]:
print(file_list)

['1', '2', '3', '4']


In [18]:
type(file_list)

list

In [20]:
print(file_list[1])

2


In [22]:
# file_list.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [26]:
# shutil.copy(r"1.txt",r"box/1.txt")

fl=file_list[1]+".txt"

print(fl)

2.txt


In [27]:
shutil.copy(fl,r"box/2.txt")

'box/2.txt'

In [30]:
next_dir="box"

In [31]:
shutil.rmtree(next_dir)
os.mkdir(next_dir)

In [45]:
file_list=np.array(file_list)

In [33]:
file_list

array(['1', '2', '3', '4'], dtype='<U1')

In [36]:
fs=np.where(file_list=='2')

In [39]:
fe=np.where(file_list=='4')

In [40]:
print(fs)
print(fe)

(array([1], dtype=int64),)
(array([3], dtype=int64),)


In [47]:
file_list_get=list()
file_list_get=np.array(file_list_get)

In [52]:
print(file_list.dtype)

<U1


In [54]:
file_list=file_list.astype(np.int)

<ipython-input-54-8f430a47c800>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  file_list=file_list.astype(np.int)


In [55]:
file_list.dtype

dtype('int32')

In [62]:
file_list[(file_list <=4) & (file_list>=2) ]

array([2, 3, 4])

In [51]:
data = np.array([100, 200, 300, 400, 500])

print(data.dtype)

int32


In [ ]:
data[data < 300]